In [1]:
import os
os.environ["BRASA_DATA_PATH"] = "D:\\brasa"

import sys
sys.path.append('..')

from datetime import datetime

import numpy as np
import pandas as pd

import brasa

In [3]:
len(brasa.get_symbols("company-trading-name"))

406

In [28]:
brasa.get_dataset("b3-companies-info").to_table().to_pandas()

,asset_name,refdate,stock_capital,quoted_per_shar_since,common_shares_form,preferred_shares_form,has_common,has_preferred,round_lot,trading_name,number_common_shares,number_preferred_shares,total_number_shares,code_cvm,segment
0,A6OP,2023-12-20,1.000000e+00,2023-04-25,Escritural,,True,False,100,ACESSOPAR,1,0,1,0,BOLSA
1,AALR,2023-12-20,6.353720e+08,2016-10-14,Escritural,Escritural,True,True,100,ALLIAR,118292816,0,118292816,24058,NM
2,ABCB,2023-12-20,4.472131e+09,2007-07-25,Escritural,Escritural,True,True,100,ABC BRASIL,119010510,117925586,236936096,20958,N2
3,ABEV,2023-12-20,5.817793e+10,2013-11-01,Escritural,,True,False,100,AMBEV S/A,15753833284,0,15753833284,23264,BOLSA
4,AERI,2023-12-20,9.119750e+08,2020-10-20,Escritural,,True,False,100,AERIS,1242403933,0,1242403933,25283,NM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
521,WNBR,2023-12-20,1.052593e+08,2020-10-08,Escritural,,True,False,100,WINE,86540918,0,86540918,25852,MB
522,YBRA,2023-12-20,4.665090e+09,2023-06-28,Escritural,Escritural,True,True,100,YBYRA S/A,116574000,116574000,233148000,16705,BOLSA
523,YDUQ,2023-12-20,1.139887e+09,2007-07-30,Escritural,Escritural,True,True,100,YDUQS PART,309088851,0,309088851,21016,NM
524,YOUC,2023-12-20,7.534782e+07,2020-06-25,Escritural,,True,False,100,YOU INC,32317787,0,32317787,0,BOLSA
525,ZAMP,2023-12-20,1.461068e+09,2017-11-29,Escritural,,True,False,100,ZAMP S.A.,275355447,0,275355447,24317,NM

In [27]:
df = brasa.get_dataset("b3-company-info-report").scanner(columns=["code", "refdate"]).to_table().to_pandas()
df = df.groupby(["code"], sort=True).last().reset_index()
df

     code     refdate
0    A6OP  2023-12-20
1    AALR  2023-12-20
2    ABCB  2023-12-20
3    ABEV  2023-12-20
4    AERI  2023-12-20
..    ...         ...
521  WNBR  2023-12-20
522  YBRA  2023-12-20
523  YDUQ  2023-12-20
524  YOUC  2023-12-20
525  ZAMP  2023-12-20

[526 rows x 2 columns]

In [31]:
import pyarrow
import pyarrow.compute as pc

df = brasa.get_dataset("b3-companies-info")\
    .filter(pc.field("code_cvm") != 0)\
    .scanner(columns=["code_cvm", "refdate"])\
    .to_table().to_pandas()
df = df.groupby(["code_cvm"], sort=True).last().reset_index()

df.code_cvm.unique()

array([    94,    183,    701,    906,    922,   1023,   1120,   1155,
         1171,   1201,   1210,   1228,   1244,   1270,   1309,   1325,
         1384,   1520,   1562,   1570,   1694,   2100,   2429,   2437,
         2453,   2461,   3050,   3069,   3077,   3115,   3158,   3190,
         3298,   3395,   3654,   3891,   3980,   4030,   4081,   4146,
         4170,   4324,   4537,   4669,   4693,   4707,   4723,   4820,
         4863,   5207,   5258,   5312,   5380,   5410,   5762,   5770,
         6041,   6076,   6173,   6211,   6343,   6505,   6629,   6700,
         7510,   7544,   7595,   7617,   7811,   7870,   8133,   8192,
         8397,   8427,   8451,   8540,   8575,   8656,   8672,   8753,
         8818,   8893,   9067,   9083,   9342,   9393,   9415,   9512,
         9539,   9954,   9989,  10456,  10880,  11070,  11223,  11231,
        11258,  11312,  11398,  11479,  11592,  11762,  11932,  11975,
        11991,  12122,  12190,  12572,  12653,  12696,  12823,  13285,
        13366,  13439,  13447,  13471,  13765,  13773,  13781,  13854,
        13986,  14109,  14206,  14311,  14320,  14346,  14443,  14451,
        14460,  14524,  14605,  14664,  14818,  14826,  14869,  15091,
        15253,  15300,  15369,  15423,  15458,  15539,  15636,  15784,
        16101,  16217,  16284,  16292,  16306,  16438,  16586,  16608,
        16616,  16624,  16632,  16659,  16705,  16748,  16861,  16950,
        16993,  17329,  17450,  17485,  17671,  17752,  17884,  17892,
        17949,  17965,  17973,  18139,  18309,  18333,  18368,  18376,
        18414,  18465,  18538,  18597,  18627,  18660,  18708,  18724,
        18775,  18821,  19100,  19119,  19208,  19232,  19305,  19330,
        19348,  19445,  19453,  19569,  19615,  19623,  19658,  19739,
        19836,  19879,  19992,  20010,  20028,  20036,  20044,  20052,
        20060,  20087,  20125,  20257,  20338,  20346,  20362,  20370,
        20435,  20451,  20478,  20516,  20524,  20532,  20567,  20575,
        20605,  20613,  20621,  20630,  20648,  20702,  20710,  20745,
        20770,  20788,  20800,  20877,  20915,  20931,  20958,  20966,
        20982,  20990,  21008,  21016,  21040,  21067,  21091,  21130,
        21148,  21180,  21199,  21237,  21334,  21342,  21350,  21393,
        21431,  21440,  21490,  21610,  21636,  21687,  21733,  21881,
        22012,  22020,  22047,  22055,  22179,  22187,  22217,  22349,
        22357,  22365,  22454,  22470,  22497,  22519,  22586,  22608,
        22616,  22675,  22780,  22985,  23159,  23175,  23221,  23248,
        23264,  23272,  23302,  23310,  23507,  23523,  23574,  23590,
        23612,  23795,  23817,  23825,  23981,  24058,  24112,  24171,
        24180,  24228,  24236,  24260,  24279,  24295,  24317,  24392,
        24546,  24600,  24627,  24660,  24694,  24716,  24759,  24783,
        24805,  24821,  24848,  24872,  24902,  24910,  24929,  24953,
        24961,  25003,  25011,  25038,  25046,  25062,  25070,  25089,
        25100,  25119,  25127,  25160,  25186,  25208,  25232,  25259,
        25275,  25283,  25291,  25330,  25372,  25399,  25402,  25445,
        25453,  25461,  25496,  25500,  25518,  25526,  25534,  25542,
        25550,  25569,  25585,  25640,  25658,  25674,  25682,  25690,
        25704,  25712,  25747,  25763,  25780,  25798,  25801,  25836,
        25844,  25852,  25860,  25879,  25887,  25895,  25917,  25933,
        25950,  25984,  25992,  26000,  26026,  26034,  26050,  26069,
        26077,  26085,  26093,  26123,  26166,  26174,  26247,  26280,
        26441,  26549,  26620,  26700,  27138,  27154,  27219, 504122,
       519707, 520780, 901686, 909705, 909754, 909978, 909994, 910000,
       910075, 910083, 910273, 910679, 912923, 914549, 914739, 914796,
       916502, 917568], dtype=int64)

In [11]:

brasa.describe("b3-bvbg087-iopv_info")

refdate: datetime
index_type: unicode
symbol: unicode
security_id: int64
security_proprietary: int64
security_market: unicode
open_price: float64
min_price: float64
max_price: float64
average_price: float64
close_price: float64
last_price: float64
oscillation_val: float64

In [4]:
brasa.get_dataset("b3-equity-symbols-properties").to_table().to_pandas()

,symbol,asset_name,trading_name,company_name,code_cvm,isin,sector,subsector,segment,stock_type,exchange_segment
0,AALR3,AALR,ALLIAR,ALLIANÇA SAÚDE E PARTICIPAÇÕES S.A.,24058,BRAALRACNOR6,Saúde,Serv.Méd.Hospit..Análises e Diagnósticos,Serv.Méd.Hospit..Análises e Diagnósticos,ON,NM
1,ABCB4,ABCB,ABC BRASIL,BCO ABC BRASIL S.A.,20958,BRABCBACNPR4,Financeiro,Intermediários Financeiros,Bancos,PN,N2
2,ABEV3,ABEV,AMBEV S/A,AMBEV S.A.,23264,BRABEVACNOR1,Consumo não Cíclico,Bebidas,Cervejas e Refrigerantes,ON,BOLSA
3,AERI3,AERI,AERIS,AERIS IND. E COM. DE EQUIP. GERACAO DE ENERGIA...,25283,BRAERIACNOR4,Bens Industriais,Máquinas e Equipamentos,Máq. e Equip. Industriais,ON,NM
4,AESB3,AESB,AES BRASIL,AES BRASIL ENERGIA S.A.,25640,BRAESBACNOR7,Utilidade Pública,Energia Elétrica,Energia Elétrica,ON,NM
...,...,...,...,...,...,...,...,...,...,...,...
606,WLMM4,WLMM,WLM IND COM,WLM PART. E COMÉRCIO DE MÁQUINAS E VEÍCULOS S.A.,11070,BRWLMMACNPR3,Bens Industriais,Comércio,Material de Transporte,PN,BOLSA
608,YBRA3,YBRA,YBYRA S/A,YBYRÁ CAPITAL S.A.,16705,BRYBRAACNOR7,Outros,Outros,Outros,ON,BOLSA
609,YBRA4,YBRA,YBYRA S/A,YBYRÁ CAPITAL S.A.,16705,BRYBRAACNPR4,Outros,Outros,Outros,PN,BOLSA
610,YDUQ3,YDUQ,YDUQS PART,YDUQS PARTICIPACOES S.A.,21016,BRYDUQACNOR3,Consumo Cíclico,Diversos,Serviços Educacionais,ON,NM
611,ZAMP3,ZAMP,ZAMP S.A.,ZAMP S.A.,24317,BRZAMPACNOR5,Consumo Cíclico,Hoteis e Restaurantes,Restaurante e Similares,ON,NM

In [5]:
brasa.get_industry_sectors()

,sector,subsector,segment
0,Bens Industriais,Comércio,Material de Transporte
1,Bens Industriais,Construção e Engenharia,Construção Pesada
2,Bens Industriais,Construção e Engenharia,Engenharia Consultiva
3,Bens Industriais,Construção e Engenharia,Produtos para Construção
4,Bens Industriais,Material de Transporte,Material Aeronáutico e de Defesa
...,...,...,...
76,Tecnologia da Informação,Computadores e Equipamentos,Computadores e Equipamentos
77,Tecnologia da Informação,Programas e Serviços,Programas e Serviços
78,Utilidade Pública,Energia Elétrica,Energia Elétrica
79,Utilidade Pública,Gás,Gás
80,Utilidade Pública,Água e Saneamento,Água e Saneamento

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel("../data/Setorial B3 13-11-2023 (português).xlsx")

In [3]:
rows = []
for ix in df.index:
    if df.iloc[ix, 0] == "SETOR ECONÔMICO":
        continue
    if not pd.isna(df.iloc[ix, 0]):
        sector = df.iloc[ix, 0]
    if not pd.isna(df.iloc[ix, 1]):
        subsector = df.iloc[ix, 1]
    if not pd.isna(df.iloc[ix, 2]) and pd.isna(df.iloc[ix, 3]) and pd.isna(df.iloc[ix, 4]):
        segment = df.iloc[ix, 2]
    if not pd.isna(df.iloc[ix, 2]) and not pd.isna(df.iloc[ix, 3]):
        row = (sector, subsector, segment, df.iloc[ix, 3])
        rows.append(row)

df_sectors = pd.DataFrame(rows, columns=["sector", "subsector", "segment", "asset_name"])
df_sectors

,sector,subsector,segment,asset_name
0,"Petróleo, Gás e Biocombustíveis","Petróleo, Gás e Biocombustíveis","Exploração, Refino e Distribuição",RRRP
1,"Petróleo, Gás e Biocombustíveis","Petróleo, Gás e Biocombustíveis","Exploração, Refino e Distribuição",CSAN
2,"Petróleo, Gás e Biocombustíveis","Petróleo, Gás e Biocombustíveis","Exploração, Refino e Distribuição",ENAT
3,"Petróleo, Gás e Biocombustíveis","Petróleo, Gás e Biocombustíveis","Exploração, Refino e Distribuição",RPMG
4,"Petróleo, Gás e Biocombustíveis","Petróleo, Gás e Biocombustíveis","Exploração, Refino e Distribuição",PETR
...,...,...,...,...
427,Outros,Outros,Outros,PPAR
428,Outros,Outros,Outros,PRPT
429,Outros,Outros,Outros,OPSE
430,Outros,Outros,Outros,OPTS
431,Outros,Outros,Outros,YBRA

In [5]:
df_sectors.query("sector == 'Saúde'")

,sector,subsector,segment,asset_name
236,Saúde,Medicamentos e Outros Produtos,Medicamentos e Outros Produtos,BIOM
237,Saúde,Medicamentos e Outros Produtos,Medicamentos e Outros Produtos,NRTQ
238,Saúde,Medicamentos e Outros Produtos,Medicamentos e Outros Produtos,OFSA
239,Saúde,"Serviços Médico - Hospitalares, Análises e Dia...","Serviços Médico - Hospitalares, Análises e Dia...",AALR
240,Saúde,"Serviços Médico - Hospitalares, Análises e Dia...","Serviços Médico - Hospitalares, Análises e Dia...",DASA
241,Saúde,"Serviços Médico - Hospitalares, Análises e Dia...","Serviços Médico - Hospitalares, Análises e Dia...",FLRY
242,Saúde,"Serviços Médico - Hospitalares, Análises e Dia...","Serviços Médico - Hospitalares, Análises e Dia...",HAPV
243,Saúde,"Serviços Médico - Hospitalares, Análises e Dia...","Serviços Médico - Hospitalares, Análises e Dia...",KRSA
244,Saúde,"Serviços Médico - Hospitalares, Análises e Dia...","Serviços Médico - Hospitalares, Análises e Dia...",MATD
245,Saúde,"Serviços Médico - Hospitalares, Análises e Dia...","Serviços Médico - Hospitalares, Análises e Dia...",ODPV
246,Saúde,"Serviços Médico - Hospitalares, Análises e Dia...","Serviços Médico - Hospitalares, Análises e Dia...",ONCO
247,Saúde,"Serviços Médico - Hospitalares, Análises e Dia...","Serviços Médico - Hospitalares, Análises e Dia...",QUAL
248,Saúde,"Serviços Médico - Hospitalares, Análises e Dia...","Serviços Médico - Hospitalares, Análises e Dia...",RDOR
249,Saúde,Equipamentos,Equipamentos,BALM
250,Saúde,Equipamentos,Equipamentos,LMED
251,Saúde,Comércio e Distribuição,Medicamentos e Outros Produtos,BLAU
252,Saúde,Comércio e Distribuição,Medicamentos e Outros Produtos,DMVF
253,Saúde,Comércio e Distribuição,Medicamentos e Outros Produtos,PNVL
254,Saúde,Comércio e Distribuição,Medicamentos e Outros Produtos,HYPE
255,Saúde,Comércio e Distribuição,Medicamentos e Outros Produtos,PGMN
256,Saúde,Comércio e Distribuição,Medicamentos e Outros Produtos,PFRM
257,Saúde,Comércio e Distribuição,Medicamentos e Outros Produtos,RADL
258,Saúde,Comércio e Distribuição,Medicamentos e Outros Produtos,VVEO